spring:
  application:
    name: vertex
  datasource:
    url: jdbc:postgresql://localhost:5432/vertex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

security:
  bcrypt:
    strength: 12
  jwt:
    secret-key: ${JWT_SECRET_KEY:changeme-this-is-a-default-secret-key-for-development-only-minimum-256-bits}
    expiration: 24h
    issuer: vertex

logging:
  level:
    org.art.vertex: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
